import re
from collections import Counter, defaultdict
from pathlib import Path

from ha_theme_kit.inventory.catalog import TokenCatalog, TokenEntry
from ha_theme_kit.inventory.classification import LAYERS

DOCS_DIRECTORY = Path(__file__).resolve().parents[3] / "docs"
UNGUARDED_VAR = re.compile(r"var\(\s*(--[A-Za-z0-9_-]+)\s*\)")


def _cell(value: str | None) -> str:
    if value in (None, ""):
        return ""
    return "`" + value.replace("|", "\\|") + "`"


def _header(catalog: TokenCatalog, title: str) -> list[str]:
    return [
        f"# {title}",
        "",
        "> Generated by `ha-themes catalog` — do not edit by hand.",
        f"> Frontend `{catalog.frontend_version}` · Core `{catalog.core_version}`"
        f" · captured {catalog.captured_at}",
        "",
    ]


def find_broken_references(catalog: TokenCatalog) -> list[tuple[TokenEntry, str, str]]:
    declared = {name for name, entry in catalog.tokens.items() if entry.layer != "component"}
    broken = []
    for entry in catalog.tokens.values():
        for mode, value in (("light", entry.light), ("dark", entry.dark)):
            for referenced in UNGUARDED_VAR.findall(value or ""):
                if referenced not in declared:
                    broken.append((entry, mode, referenced))
    return broken


def render_global_reference(catalog: TokenCatalog) -> str:
    global_tokens = [entry for entry in catalog.tokens.values() if entry.layer != "component"]
    layer_counts = Counter(entry.layer for entry in global_tokens)
    lines = _header(catalog, "Global token reference")
    lines += [
        "Every CSS custom property the frontend declares on `html`, as observed in Google Chrome",
        "against a running instance. Theme keys are the token name without the leading `--`.",
        "",
        "- **Light** is the declared default. **Dark** is only filled when dark mode replaces it.",
        "- Values containing `var()` are *derived*: override the referenced token instead and",
        "  the change cascades.",
        "- **Uses** is the number of frontend chunks that read the token — a rough measure of",
        "  how much of the UI a change will touch.",
        "",
        "| Layer | Tokens |",
        "| --- | ---: |",
    ]
    lines += [
        f"| [{layer}](#{layer}) | {layer_counts[layer]} |"
        for layer in LAYERS
        if layer_counts[layer]
    ]
    broken = find_broken_references(catalog)
    if broken:
        lines += [
            "",
            "## Broken upstream references",
            "",
            "Default values that point at tokens the frontend never declares; they resolve to",
            "nothing. Themes can fix them by setting the token explicitly.",
            "",
            "| Token | Mode | Missing reference |",
            "| --- | --- | --- |",
        ]
        lines += [f"| `{entry.name}` | {mode} | `{missing}` |" for entry, mode, missing in broken]
    by_layer: dict[str, dict[str, list[TokenEntry]]] = defaultdict(lambda: defaultdict(list))
    for entry in global_tokens:
        by_layer[entry.layer][entry.group].append(entry)
    for layer, description in LAYERS.items():
        if layer not in by_layer:
            continue
        lines += ["", f"## {layer}", "", description.split(" — ", 1)[1].capitalize() + "."]
        for group, entries in sorted(by_layer[layer].items()):
            lines += [
                "",
                f"### {layer} / {group}",
                "",
                "| Token | Light | Dark | Uses |",
                "| --- | --- | --- | ---: |",
            ]
            for entry in sorted(entries, key=lambda item: item.name):
                light = entry.light
                if entry.reduced_motion:
                    light = f"{light}` (reduced motion: `{entry.reduced_motion}"
                lines.append(
                    f"| `{entry.name}` | {_cell(light)} | {_cell(entry.dark)} | {entry.consumers} |"
                )
    return "\n".join(lines) + "\n"


DYNAMIC_FAMILY_NOTES = {
    "--state-": (
        "Entity state colors. For a domain in the frontend's stateful list the first set "
        "token wins: `--state-<domain>-<device_class>-<state>-color`, "
        "`--state-<domain>-<state>-color`, `--state-<domain>-<active|inactive>-color`, "
        "`--state-<active|inactive>-color`. Any combination can be set by a theme."
    ),
    "--graph-color-": (
        "Chart series override, read with `getPropertyValue` before `--color-N`; unset by "
        "default. Use hex values: the charts parse them in JavaScript."
    ),
    "--color-": (
        "Chart, calendar and map series 1-54, cycled as `index % 54 + 1`. Read in "
        "JavaScript, so use hex values."
    ),
    "--weather-icon-": (
        "Weather icon parts (`sun`, `moon`, `rain`, `snow`, `cloud-front`, `cloud-back`) as "
        "`--weather-icon-<part>-color`, and `--weather-icon-<condition>` as a background "
        "image that replaces the icon for that condition."
    ),
}


def render_component_reference(catalog: TokenCatalog) -> str:
    components = [entry for entry in catalog.tokens.values() if entry.layer == "component"]
    groups: dict[str, list[TokenEntry]] = defaultdict(list)
    for entry in components:
        groups[entry.group].append(entry)
    lines = _header(catalog, "Component hook reference")
    lines += [
        "Custom properties that components read with `var()` but that are **not** declared",
        "globally. They are hooks: unset by default, so the component falls back to the value",
        "shown. A theme can set any of them. Found by scanning the shipped frontend bundle.",
        "",
        "Groups are sorted by reach; `md-*`, `mdc-*` and `wa-*` hooks belong to third-party",
        "components and are less stable across releases than `ha-*` hooks.",
    ]
    if catalog.dynamic_families:
        lines += [
            "",
            "## Dynamic families",
            "",
            "Names the frontend builds at runtime (template literals), so they never appear",
            "literally in the bundle. **Chunks** is how many frontend chunks build each one.",
            "",
            "| Prefix | Chunks | How it is resolved |",
            "| --- | ---: | --- |",
        ]
        lines += [
            f"| `{prefix}…` | {count} | {DYNAMIC_FAMILY_NOTES.get(prefix, '')} |"
            for prefix, count in catalog.dynamic_families.items()
            if prefix in DYNAMIC_FAMILY_NOTES
        ]
    ordered = sorted(groups.items(), key=lambda item: -sum(e.consumers for e in item[1]))
    for group, entries in ordered:
        lines += [
            "",
            f"## {group}",
            "",
            "| Token | Fallback | Uses |",
            "| --- | --- | ---: |",
        ]
        for entry in sorted(entries, key=lambda item: (-item.consumers, item.name)):
            fallback = "<br>".join(_cell(value) for value in entry.fallbacks[:3])
            lines.append(f"| `{entry.name}` | {fallback} | {entry.consumers} |")
    return "\n".join(lines) + "\n"


def write_reference_docs(catalog: TokenCatalog, directory: Path = DOCS_DIRECTORY) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    outputs = {
        directory / "tokens-global.md": render_global_reference(catalog),
        directory / "tokens-components.md": render_component_reference(catalog),
    }
    for path, content in outputs.items():
        path.write_text(content)
    return list(outputs)
